AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: API for DynamoDB
Resources:
  LambdaAPI:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./src
      Description: 'Lambda function for DynamoDB'
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          table: ORG_DTL
          rej_table: ORG_DTL_REJ
      FunctionName: 'APIDynamoDB'
      Policies: 
      - AWSLambdaExecute
      - Version: '2012-10-17'
        Statement:
         - Effect: Allow
           Action: "*"
           Resource: "*" 
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
            RequestParameters:
             - method.request.querystring.method:
                Required: true         
        PostEvent:
          Type: Api
          Properties:
            Path: /
            Method: post  
        DeleteEvent:
          Type: Api
          Properties:
            Path: /
            Method: delete 
            
  DynamoDBTable1:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "ORG_ID"
          AttributeType: "N"
          
      KeySchema:
        -
          AttributeName: "ORG_ID"
          KeyType: "HASH"

  
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
      TableName: "ORG_DTL"
      
  DynamoDBTable2:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "ORG_ID"
          AttributeType: "N"
          
      KeySchema:
        -
          AttributeName: "ORG_ID"
          KeyType: "HASH"

  
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
        
      TableName: "ORG_DTL_REJ"
